### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by gengmao**
Hi @windreamer, 

I am working on running TensorFlow in Docker container with GPU support on Mesos, and found your tfmesos project - which is awesome. Thanks for open sourcing this!
I tried to build a docker image by myself but found the Dockerfile needs some update. The parent docker image has switched to Xenial. So that I need to remove the Trusty sources, otherwise docker build failed to install deb packages. Also I'd like to install pip requirements and source locally. Could you please review and let me know if the changes are legit? 

Thanks,
Mao

### CODE REVIEW

**Comment by windreamer** [comment]
Thx for this PR!
I know install pip requirements and package according to local version is convenient  for development. But I think an editable installation into `/opt/src/tfmesos` is not what I expect. we still prefer install into the default system path.
Installing master version in remote repository is just based an idea that I want the `Dockerfile` can be standalone without the whole repository structure. But I am OK we decide to install locally, with a non-editable way, if this is a better approach.

**Comment by gengmao** [comment]
Hello @windreamer, thanks for quick feedback. 
It still installs binaries into the default system path - /usr/local/bin. Unfortunately `docker build` don't support `-v` option so that I have to `ADD` local sources into container then install them. How about I add a `rm -rf /opt/src/mesos` after `pip install`? The image size won't shrink as the ADD layer, but at least there won't be editable sources left in container.

**Comment by windreamer** [comment]
@gengmao if it is OK to you, I would prefer seperate this PR into 2 parts: the `sources.list` looks good to me, the locallly installation part I needs more time to figure out a better way.
Thanks for the kindly help.

**Comment by gengmao** [comment]
Sure. Let me update the PR quickly

**Comment by gengmao** [comment]
Updated

**Comment by windreamer** [comment]
LGTM

**Pull request merged**
